My Project: Telemetry Class Reference
Telemetry Class Reference
#include <Telemetry.hpp>
Public Member Functions
Telemetry (MCP2515 &mcp2515_, CarState &car_)
Construct a new Telemetry object.
void sendTelemetry ()
Sends telemetry data based on the scheduling logic.
Private Member Functions
void schedulerAdc ()
Internal helper to get and send the ADC telemetry frame.
void schedulerDigital ()
Internal helper to get and send the digital telemetry frame.
void schedulerStates ()
Internal helper to get and send the state telemetry frame.
Private Attributes
MCP2515 & mcp2515
CarState & car
uint8_t count
Static Private Attributes
static constexpr uint8_t NUM_FREQ_FRAMES = 2
static constexpr uint8_t NUM_INFREQ_FRAMES = 1
static constexpr uint8_t FRAMES_FREQ_RATIO = 10
static constexpr uint8_t MAX_FRAME_COUNTER = NUM_FREQ_FRAMES * FRAMES_FREQ_RATIO + NUM_INFREQ_FRAMES - 1
static constexpr canid_t TelemetryAdcMsg = 0x700
static constexpr canid_t TelemetryDigitalMsg = 0x701
static constexpr canid_t TelemetryStateMsg = 0x702
Detailed Description
Definition at line 21 of file Telemetry.hpp.
Constructor & Destructor Documentation
Telemetry()
Telemetry::Telemetry (MCP2515 & mcp2515_, CarState & car_)
Construct a new Telemetry object.
Parameters
mcp2515_ Reference to MCP2515 for sending CAN messages
car_ Reference to CarState
Definition at line 17 of file Telemtry.cpp.
Member Function Documentation
schedulerAdc()
void Telemetry::schedulerAdc () private
Internal helper to get and send the ADC telemetry frame.
Definition at line 25 of file Telemtry.cpp.
References CarState::adc, car, mcp2515, and TelemetryFrameAdc::toCanFrame().
Referenced by sendTelemetry().
schedulerDigital()
void Telemetry::schedulerDigital () private
Internal helper to get and send the digital telemetry frame.
Definition at line 34 of file Telemtry.cpp.
References car, CarState::digital, mcp2515, and TelemetryFrameDigital::toCanFrame().
Referenced by sendTelemetry().
schedulerStates()
void Telemetry::schedulerStates () private
Internal helper to get and send the state telemetry frame.
Definition at line 43 of file Telemtry.cpp.
References car, mcp2515, CarState::state, and TelemetryFrameState::toCanFrame().
Referenced by sendTelemetry().
sendTelemetry()
void Telemetry::sendTelemetry ()
Sends telemetry data based on the scheduling logic.
Definition at line 52 of file Telemtry.cpp.
References count, FRAMES_FREQ_RATIO, MAX_FRAME_COUNTER, schedulerAdc(), schedulerDigital(), and schedulerStates().
Referenced by schedulerTelemetry().
Member Data Documentation
car
CarState& Telemetry::car private
Reference to CarState
Definition at line 29 of file Telemetry.hpp.
Referenced by schedulerAdc(), schedulerDigital(), and schedulerStates().
count
uint8_t Telemetry::count private
Counter number of times message sent
Definition at line 31 of file Telemetry.hpp.
Referenced by sendTelemetry().
FRAMES_FREQ_RATIO
constexpr uint8_t Telemetry::FRAMES_FREQ_RATIO = 10 static constexpr private
Ratio of frame frequencies
Definition at line 39 of file Telemetry.hpp.
Referenced by sendTelemetry().
MAX_FRAME_COUNTER
constexpr uint8_t Telemetry::MAX_FRAME_COUNTER = NUM_FREQ_FRAMES * FRAMES_FREQ_RATIO + NUM_INFREQ_FRAMES - 1 static constexpr private
Count resets at this value, total frames per cycle - 1 because tree planting
Definition at line 40 of file Telemetry.hpp.
Referenced by sendTelemetry().
mcp2515
MCP2515& Telemetry::mcp2515 private
Reference to MCP2515 for sending CAN messages
Definition at line 28 of file Telemetry.hpp.
Referenced by schedulerAdc(), schedulerDigital(), and schedulerStates().
NUM_FREQ_FRAMES
constexpr uint8_t Telemetry::NUM_FREQ_FRAMES = 2 static constexpr private
Number of frequent telemetry frames to send
Definition at line 37 of file Telemetry.hpp.
NUM_INFREQ_FRAMES
constexpr uint8_t Telemetry::NUM_INFREQ_FRAMES = 1 static constexpr private
Number of infrequent telemetry frames to send, must be 1 because of how the fast modulo logic works
Definition at line 38 of file Telemetry.hpp.
TelemetryAdcMsg
constexpr canid_t Telemetry::TelemetryAdcMsg = 0x700 static constexpr private
Telemetry: ADC readings message
Definition at line 46 of file Telemetry.hpp.
TelemetryDigitalMsg
constexpr canid_t Telemetry::TelemetryDigitalMsg = 0x701 static constexpr private
Telemetry: Digital signals message
Definition at line 47 of file Telemetry.hpp.
TelemetryStateMsg
constexpr canid_t Telemetry::TelemetryStateMsg = 0x702 static constexpr private
Telemetry: Car state message
Definition at line 48 of file Telemetry.hpp.
The documentation for this class was generated from the following files:
lib/Telemetry/Telemetry.hpp
lib/Telemetry/Telemtry.cpp