Red Bird Racing VCU: BMS Class Reference
BMS Class Reference
BMS class for managing the Accumulator (Kclear BMS) via CAN bus.
#include <BMS.hpp>
Public Member Functions
BMS (MCP2515 &bms_can_, CarState &car_)
Construct a new BMS object, initing car.pedal.status.bits.hv_ready to false.
bool hvReady () const
Returns true if HV has been started.
void checkHv ()
Attempts to start HV. First check BMS is in standby(3) state, then send the HV start command. Keep sending the command until the BMS state changes to precharge(4). Sets car.pedal.status.bits.hv_ready to true when BMS state changes to run(5).
Private Attributes
MCP2515 & bms_can
can_frame rx_bms_msg
CarState & car
Detailed Description
BMS class for managing the Accumulator (Kclear BMS) via CAN bus.
Definition at line 46 of file BMS.hpp.
Constructor & Destructor Documentation
BMS()
BMS::BMS (MCP2515 & bms_can_, CarState & car_)
Construct a new BMS object, initing car.pedal.status.bits.hv_ready to false.
Parameters
bms_can_ Reference to MCP2515 for BMS CAN bus
car_ Reference to boolean, prefer use CarState member. True if HV has been started, for state machine
Definition at line 32 of file BMS.cpp.
References TelemetryFramePedal::StateByteStatus::bits, car, TelemetryFramePedal::StateByteStatus::Bits::hv_ready, CarState::pedal, and TelemetryFramePedal::status.
Member Function Documentation
checkHv()
void BMS::checkHv ()
Attempts to start HV. First check BMS is in standby(3) state, then send the HV start command. Keep sending the command until the BMS state changes to precharge(4). Sets car.pedal.status.bits.hv_ready to true when BMS state changes to run(5).
Definition at line 45 of file BMS.cpp.
References TelemetryFramePedal::StateByteStatus::bits, bms_can, BMS_INFO_EXT, TelemetryFramePedal::StateByteStatus::Bits::bms_no_msg, TelemetryFramePedal::StateByteStatus::Bits::bms_wrong_id, car, DBG_BMS_STATUS(), DBGLN_GENERAL(), TelemetryFramePedal::StateByteStatus::Bits::hv_ready, CarState::pedal, rx_bms_msg, start_hv_msg, and TelemetryFramePedal::status.
Referenced by scheduler_bms().
hvReady()
bool BMS::hvReady () const inline
Returns true if HV has been started.
Returns
true if HV started, false otherwise
Definition at line 54 of file BMS.hpp.
References TelemetryFramePedal::StateByteStatus::bits, car, TelemetryFramePedal::StateByteStatus::Bits::hv_ready, CarState::pedal, and TelemetryFramePedal::status.
Member Data Documentation
bms_can
MCP2515& BMS::bms_can private
Reference to MCP2515 for BMS CAN bus
Definition at line 58 of file BMS.hpp.
Referenced by checkHv().
car
CarState& BMS::car private
Reference to CarState, for the status flags and setting BMS data
Definition at line 65 of file BMS.hpp.
Referenced by BMS(), checkHv(), and hvReady().
rx_bms_msg
can_frame BMS::rx_bms_msg private
Initial value:
= {
        0,
        0,
        {0},
    }
Local storage for received BMS CAN frame
Definition at line 60 of file BMS.hpp.
Referenced by checkHv().
The documentation for this class was generated from the following files:
ee_sw_vcu_2025/lib/BMS/BMS.hpp
ee_sw_vcu_2025/lib/BMS/BMS.cpp