My Project: lib/Debug/Debug.h File Reference
Debug.h File Reference
#include "Enums.h"
Macros
#define DEBUG true
#define DEBUG_SERIAL false && DEBUG
#define DEBUG_CAN false && DEBUG
#define DEBUG_THROTTLE true && DEBUG
#define DEBUG_THROTTLE_IN true && DEBUG_THROTTLE
#define DEBUG_THROTTLE_OUT true && DEBUG_THROTTLE
#define DEBUG_THROTTLE_FAULT true && DEBUG_THROTTLE
#define DEBUG_BRAKE true && DEBUG
#define DEBUG_BRAKE_IN true && DEBUG_BRAKE
#define DEBUG_BRAKE_FAULT true && DEBUG_BRAKE
#define DEBUG_GENERAL true
#define DEBUG_STATUS true
#define DEBUG_STATUS_CAR true && DEBUG_STATUS
#define DEBUG_STATUS_BRAKE true && DEBUG_STATUS
#define DEBUG_HALL_SENSOR true && DEBUG
Functions
void DBG_THROTTLE (const char *x)
Prints a throttle debug message to the serial console.
void DBGLN_THROTTLE (const char *x)
Prints a line to the serial console for throttle debug.
void DBG_GENERAL (const char *x)
Prints a general debug message to the serial console.
void DBGLN_GENERAL (const char *x)
Prints a line to the serial console for general debug.
void DBG_STATUS (const char *x)
Prints a status message to the serial console.
void DBGLN_STATUS (const char *x)
Prints a line to the serial console for status debug.
void DBG_THROTTLE_IN (uint16_t pedal_filtered_1, uint16_t pedal_filtered_2, uint16_t pedal_filtered_final, uint16_t brake)
Sends throttle pedal input debug info via CAN or serial (if enabled).
void DBG_THROTTLE_OUT (uint16_t throttle_final, int16_t throttle_torque_val)
Sends throttle output debug info via CAN or serial (if enabled).
void DBG_THROTTLE_FAULT (pedal_fault_status fault_status, uint16_t value)
Sends throttle fault debug info via CAN or serial (if enabled). Overloads for fault status with or without value.
void DBG_THROTTLE_FAULT (pedal_fault_status fault_status)
void DBG_STATUS_CAR (main_car_status car_status)
Sends car status debug info via CAN or serial (if enabled).
void DBG_BRAKE_FAULT (pedal_fault_status fault_status, uint16_t value)
Sends brake fault debug info via CAN or serial (if enabled). Overloads for fault status with or without value.
void DBG_BMS_STATUS (BMS_status BMS_status)
Sends BMS debug info via CAN or serial (if enabled).
void DBG_HALL_SENSOR (uint16_t hall_sensor_value)
Send hall sensor debug info via CAN.
Macro Definition Documentation
DEBUG
#define DEBUG true
Definition at line 7 of file Debug.h.
DEBUG_BRAKE
#define DEBUG_BRAKE true && DEBUG
Definition at line 23 of file Debug.h.
DEBUG_BRAKE_FAULT
#define DEBUG_BRAKE_FAULT true && DEBUG_BRAKE
Definition at line 25 of file Debug.h.
DEBUG_BRAKE_IN
#define DEBUG_BRAKE_IN true && DEBUG_BRAKE
Definition at line 24 of file Debug.h.
DEBUG_CAN
#define DEBUG_CAN false && DEBUG
Definition at line 9 of file Debug.h.
DEBUG_GENERAL
#define DEBUG_GENERAL true
Definition at line 26 of file Debug.h.
DEBUG_HALL_SENSOR
#define DEBUG_HALL_SENSOR true && DEBUG
Definition at line 30 of file Debug.h.
DEBUG_SERIAL
#define DEBUG_SERIAL false && DEBUG
Definition at line 8 of file Debug.h.
DEBUG_STATUS
#define DEBUG_STATUS true
Definition at line 27 of file Debug.h.
DEBUG_STATUS_BRAKE
#define DEBUG_STATUS_BRAKE true && DEBUG_STATUS
Definition at line 29 of file Debug.h.
DEBUG_STATUS_CAR
#define DEBUG_STATUS_CAR true && DEBUG_STATUS
Definition at line 28 of file Debug.h.
DEBUG_THROTTLE
#define DEBUG_THROTTLE true && DEBUG
Definition at line 19 of file Debug.h.
DEBUG_THROTTLE_FAULT
#define DEBUG_THROTTLE_FAULT true && DEBUG_THROTTLE
Definition at line 22 of file Debug.h.
DEBUG_THROTTLE_IN
#define DEBUG_THROTTLE_IN true && DEBUG_THROTTLE
Definition at line 20 of file Debug.h.
DEBUG_THROTTLE_OUT
#define DEBUG_THROTTLE_OUT true && DEBUG_THROTTLE
Definition at line 21 of file Debug.h.
Function Documentation
DBG_BMS_STATUS()
void DBG_BMS_STATUS (BMS_status BMS_status) inline
Sends BMS debug info via CAN or serial (if enabled).
Parameters
BMS_status The BMS status enum.
Definition at line 205 of file Debug.h.
{
#if DEBUG_BRAKE_FAULT && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::status_bms(BMS_status);
#endif
#if DEBUG_CAN
    Debug_CAN::status_bms(BMS_status);
#endif
#endif
}
References Debug_CAN::status_bms(), and Debug_Serial::status_bms().
Referenced by BMS::check_hv().
DBG_BRAKE_FAULT()
void DBG_BRAKE_FAULT (pedal_fault_status fault_status, uint16_t value) inline
Sends brake fault debug info via CAN or serial (if enabled). Overloads for fault status with or without value.
Parameters
fault_status The fault status enum.
value Optional float value for fault.
Definition at line 189 of file Debug.h.
{
#if DEBUG_BRAKE_FAULT && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::brake_fault(fault_status, value);
#endif
#if DEBUG_CAN
    Debug_CAN::brake_fault(fault_status, value);
#endif
#endif
}
References Debug_CAN::brake_fault(), and Debug_Serial::brake_fault().
Referenced by Pedal::brake_torque_mapping().
DBG_GENERAL()
void DBG_GENERAL (const char * x) inline
Prints a general debug message to the serial console.
Parameters
x The message to print.
Definition at line 60 of file Debug.h.
{
#if DEBUG_GENERAL && DEBUG_SERIAL
    Debug_Serial::print(x);
#endif
}
References Debug_Serial::print().
DBG_HALL_SENSOR()
void DBG_HALL_SENSOR (uint16_t hall_sensor_value) inline
Send hall sensor debug info via CAN.
Parameters
hall_sensor_value The hall sensor value.
Definition at line 221 of file Debug.h.
{
#if DEBUG_HALL_SENSOR && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::hall_sensor(hall_sensor_value);
#endif
#if DEBUG_CAN
    Debug_CAN::hall_sensor(hall_sensor_value);
#endif
#endif
}
References Debug_CAN::hall_sensor(), and Debug_Serial::hall_sensor().
DBG_STATUS()
void DBG_STATUS (const char * x) inline
Prints a status message to the serial console.
Parameters
x The message to print.
Definition at line 82 of file Debug.h.
{
#if DEBUG_STATUS && DEBUG_SERIAL
    Debug_Serial::print(x);
#endif
}
References Debug_Serial::print().
DBG_STATUS_CAR()
void DBG_STATUS_CAR (main_car_status car_status) inline
Sends car status debug info via CAN or serial (if enabled).
Parameters
car_status Car status enum value.
Definition at line 171 of file Debug.h.
{
#if DEBUG_STATUS_CAR && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::status_car(car_status);
#endif
#if DEBUG_CAN
    Debug_CAN::status_car(car_status);
#endif
#endif
}
References Debug_CAN::status_car(), and Debug_Serial::status_car().
Referenced by loop(), and setup().
DBG_THROTTLE()
void DBG_THROTTLE (const char * x) inline
Prints a throttle debug message to the serial console.
Parameters
x The message to print.
Definition at line 38 of file Debug.h.
{
#if DEBUG_THROTTLE && DEBUG_SERIAL
    Debug_Serial::print(x);
#endif
}
References Debug_Serial::print().
DBG_THROTTLE_FAULT() [1/2]
void DBG_THROTTLE_FAULT (pedal_fault_status fault_status) inline
Definition at line 155 of file Debug.h.
{
#if DEBUG_THROTTLE_FAULT && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::throttle_fault(fault_status);
#endif
#if DEBUG_CAN
    Debug_CAN::throttle_fault(fault_status);
#endif
#endif
}
References Debug_CAN::throttle_fault(), and Debug_Serial::throttle_fault().
DBG_THROTTLE_FAULT() [2/2]
void DBG_THROTTLE_FAULT (pedal_fault_status fault_status, uint16_t value) inline
Sends throttle fault debug info via CAN or serial (if enabled). Overloads for fault status with or without value.
Parameters
fault_status The fault status enum.
value Optional float value for fault.
Definition at line 143 of file Debug.h.
{
#if DEBUG_THROTTLE_FAULT && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::throttle_fault(fault_status, value);
#endif
#if DEBUG_CAN
    Debug_CAN::throttle_fault(fault_status, value);
#endif
#endif
}
References Debug_CAN::throttle_fault(), and Debug_Serial::throttle_fault().
Referenced by Pedal::brake_torque_mapping(), Pedal::check_pedal_fault(), Pedal::pedal_update(), and Pedal::throttle_torque_mapping().
DBG_THROTTLE_IN()
void DBG_THROTTLE_IN (uint16_t pedal_filtered_1, uint16_t pedal_filtered_2, uint16_t pedal_filtered_final, uint16_t brake) inline
Sends throttle pedal input debug info via CAN or serial (if enabled).
Parameters
pedal_filtered_1 Filtered value from pedal 1.
pedal_filtered_2 Filtered value from pedal 2.
pedal_filtered_final Final filtered value.
Definition at line 108 of file Debug.h.
{
#if DEBUG_THROTTLE_IN && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::throttle_in(pedal_filtered_1, pedal_filtered_2, pedal_filtered_final, brake);
#endif
#if DEBUG_CAN
    Debug_CAN::throttle_in(pedal_filtered_1, pedal_filtered_2, pedal_filtered_final, brake);
#endif
#endif
}
References Debug_CAN::throttle_in(), and Debug_Serial::throttle_in().
Referenced by Pedal::check_pedal_fault().
DBG_THROTTLE_OUT()
void DBG_THROTTLE_OUT (uint16_t throttle_final, int16_t throttle_torque_val) inline
Sends throttle output debug info via CAN or serial (if enabled).
Parameters
throttle_final Final throttle value.
throttle_torque_val Output torque value.
Definition at line 125 of file Debug.h.
{
#if DEBUG_THROTTLE_OUT && (DEBUG_SERIAL || DEBUG_CAN)
#if DEBUG_SERIAL
    Debug_Serial::throttle_out(throttle_final, throttle_torque_val);
#endif
#if DEBUG_CAN
    Debug_CAN::throttle_out(throttle_final, throttle_torque_val);
#endif
#endif
}
References Debug_CAN::throttle_out(), and Debug_Serial::throttle_out().
Referenced by Pedal::pedal_can_frame_update().
DBGLN_GENERAL()
void DBGLN_GENERAL (const char * x) inline
Prints a line to the serial console for general debug.
Parameters
x The message to print.
Definition at line 71 of file Debug.h.
{
#if DEBUG_GENERAL && DEBUG_SERIAL
    Debug_Serial::println(x);
#endif
}
References Debug_Serial::println().
Referenced by BMS::check_hv(), and setup().
DBGLN_STATUS()
void DBGLN_STATUS (const char * x) inline
Prints a line to the serial console for status debug.
Parameters
x The message to print.
Definition at line 93 of file Debug.h.
{
#if DEBUG_STATUS && DEBUG_SERIAL
    Debug_Serial::println(x);
#endif
}
References Debug_Serial::println().
Referenced by setup().
DBGLN_THROTTLE()
void DBGLN_THROTTLE (const char * x) inline
Prints a line to the serial console for throttle debug.
Parameters
x The message to print.
Definition at line 49 of file Debug.h.
{
#if DEBUG_THROTTLE && DEBUG_SERIAL
    Debug_Serial::println(x);
#endif
}
References Debug_Serial::println().
Referenced by loop(), and Pedal::pedal_can_frame_update().