My Project: src/main.cpp File Reference
main.cpp File Reference
#include <Arduino.h>
#include "boardConf.h"
#include "Pedal.h"
#include "BMS.h"
#include <mcp2515.h>
#include "Debug.h"
#include "Enums.h"
#include "car_state.h"
#include "Scheduler.hpp"
Macros
#define mcp2515_motor mcp2515_DL
#define NUM_MCP 3
Functions
MCP2515 mcp2515_motor (CS_CAN_MOTOR)
MCP2515 mcp2515_BMS (CS_CAN_BMS)
MCP2515 mcp2515_DL (CS_CAN_DL)
void scheduler_pedal (MCP2515 *mcp2515_)
void scheduler_bms (MCP2515 *mcp2515_)
void setup ()
Setup function for initializing the VCU system. Initializes MCP2515s, IO pins, as well as own modules such as Pedal and Debug.
void loop ()
Main loop function for the VCU system. Handles car state transitions, pipes dataflow between modules.
Variables
constexpr uint8_t INPUT_COUNT = 5
constexpr uint8_t pins_in [INPUT_COUNT] = {DRIVE_MODE_BTN, BRAKE_IN, APPS_5V, APPS_3V3, HALL_SENSOR}
constexpr uint8_t OUTPUT_COUNT = 4
constexpr uint8_t pins_out [OUTPUT_COUNT] = {FRG, BRAKE_LIGHT, BUZZER, BMS_FAILED_LED}
BMS bms & mcp2515_BMS
MCP2515 * MCPS [3] = {& mcp2515_DL , &mcp2515_BMS, &mcp2515_DL}
struct can_frame tx_throttle_msg
constexpr uint16_t STARTING_MILLIS = 2000
constexpr uint16_t BUSSIN_MILLIS = 2000
constexpr uint16_t BMS_MILLIS = 10000
constexpr uint16_t BRAKE_THRESHOLD = 130
bool brake_pressed = false
struct car_state main_car_state
Global car state structure.
Pedal pedal
Scheduler< 4, 3 > scheduler (10000, 1000, MCPS)
Macro Definition Documentation
mcp2515_motor
#define mcp2515_motor mcp2515_DL
Definition at line 39 of file main.cpp.
NUM_MCP
#define NUM_MCP 3
Definition at line 41 of file main.cpp.
Function Documentation
loop()
void loop ()
Main loop function for the VCU system. Handles car state transitions, pipes dataflow between modules.
Definition at line 144 of file main.cpp.
{
    // DBG_HALL_SENSOR(analogRead(HALL_SENSOR));
    main_car_state.millis = millis();
    pedal.pedal_update(&main_car_state, analogRead(APPS_5V), analogRead(APPS_3V3), analogRead(BRAKE_IN));
    brake_pressed = static_cast<uint16_t>(analogRead(BRAKE_IN)) >= BRAKE_THRESHOLD;
    digitalWrite(BRAKE_LIGHT, brake_pressed ? HIGH : LOW);
    scheduler.update(*micros);
    if (main_car_state.fault_force_stop)
    {
        main_car_state.car_status = INIT; // safety, later change to fault status
        digitalWrite(BUZZER, LOW);        // Turn off buzzer
        digitalWrite(FRG, LOW);           // Turn off drive mode LED
        return;                           // If fault force stop is active, do not proceed with the rest of the loop
        // pedal is still being updated, data can still be gathered and sent through CAN/serial
    }
    switch (main_car_state.car_status)
    {
    case DRIVE:
        // Pedal update
        // Send pedal value through canbus
        // already scheduled
        return; // no need logic to check if pedal on, car started
    // do not return here if not in DRIVE mode, else can't detect pedal being on while starting
    case INIT:
        DBGLN_THROTTLE("Stopping motor: INIT.");
        if (digitalRead(DRIVE_MODE_BTN) == BUTTON_ACTIVE && brake_pressed)
        {
            main_car_state.car_status = STARTIN;
            main_car_state.car_status_millis_counter = main_car_state.millis;
            // scheduler.add_task(MCP_BMS, scheduler_bms, 5); // check for HV ready, if not start it
            DBG_STATUS_CAR(main_car_state.car_status);
        }
        break;
    case STARTIN:
        pedal.pedal_can_frame_stop_motor(&tx_throttle_msg);
        DBGLN_THROTTLE("Stopping motor: STARTIN.");
        mcp2515_motor.sendMessage(&tx_throttle_msg);
        if (digitalRead(DRIVE_MODE_BTN) != BUTTON_ACTIVE || !brake_pressed)
        {
            main_car_state.car_status = INIT;
            main_car_state.car_status_millis_counter = main_car_state.millis; // safety
            DBG_STATUS_CAR(main_car_state.car_status);
        }
        else if (main_car_state.millis - main_car_state.car_status_millis_counter >= STARTING_MILLIS)
        {
            // scheduler.remove_task(MCP_BMS, scheduler_bms); // stop checking BMS HV ready
            if (bms.hv_ready()) // if HV not started, return to INIT
            {
                main_car_state.car_status = INIT;
                main_car_state.car_status_millis_counter = main_car_state.millis; // safety
                DBG_STATUS_CAR(main_car_state.car_status);
                break;
            }
            if (main_car_state.millis - main_car_state.car_status_millis_counter >= BMS_MILLIS)
            {
                main_car_state.car_status = BUSSIN;
                main_car_state.car_status_millis_counter = main_car_state.millis; // safety
                DBG_STATUS_CAR(main_car_state.car_status);
                break;
            }
        }
        break;
    case BUSSIN:
        digitalWrite(BUZZER, HIGH); // Turn on buzzer
        if (main_car_state.millis - main_car_state.car_status_millis_counter >= BUSSIN_MILLIS)
        {
            digitalWrite(BUZZER, LOW);
            digitalWrite(FRG, HIGH);
            main_car_state.car_status = DRIVE;
            DBG_STATUS_CAR(main_car_state.car_status);
        }
        break;
    default:
        DBG_STATUS_CAR(main_car_state.car_status);
        break;
    }
    // DRIVE mode has already returned, if reached here, then means car isn't in DRIVE
    if (main_car_state.pedal_final > PEDAL_1_LU)
    {
        main_car_state.car_status = INIT;
        main_car_state.car_status_millis_counter = main_car_state.millis; // Set to current time, in case any counter relies on this
        DBG_STATUS_CAR(main_car_state.car_status);
    }
}
References APPS_3V3, APPS_5V, BMS_MILLIS, BRAKE_IN, BRAKE_LIGHT, brake_pressed, BRAKE_THRESHOLD, BUSSIN, BUSSIN_MILLIS, BUTTON_ACTIVE, BUZZER, car_state::car_status, car_state::car_status_millis_counter, DBG_STATUS_CAR(), DBGLN_THROTTLE(), DRIVE, DRIVE_MODE_BTN, car_state::fault_force_stop, FRG, INIT, main_car_state, mcp2515_motor, car_state::millis, pedal, PEDAL_1_LU, Pedal::pedal_can_frame_stop_motor(), car_state::pedal_final, Pedal::pedal_update(), scheduler, STARTIN, STARTING_MILLIS, and tx_throttle_msg.
mcp2515_BMS()
MCP2515 mcp2515_BMS (CS_CAN_BMS)
mcp2515_DL()
MCP2515 mcp2515_DL (CS_CAN_DL)
Referenced by setup().
mcp2515_motor()
MCP2515 mcp2515_motor (CS_CAN_MOTOR)
scheduler_bms()
void scheduler_bms (MCP2515 * mcp2515_)
Definition at line 85 of file main.cpp.
{
    bms.check_hv(mcp2515_);
}
scheduler_pedal()
void scheduler_pedal (MCP2515 * mcp2515_)
Definition at line 79 of file main.cpp.
{
    static can_frame tx_msg;
    pedal.pedal_can_frame_update(&tx_msg, &main_car_state);
    mcp2515_->sendMessage(&tx_msg);
}
References main_car_state, pedal, and Pedal::pedal_can_frame_update().
Referenced by setup().
setup()
void setup ()
Setup function for initializing the VCU system. Initializes MCP2515s, IO pins, as well as own modules such as Pedal and Debug.
Definition at line 100 of file main.cpp.
{
    pedal = Pedal();
    for (int i = 0; i < NUM_MCP; i++)
    {
        MCPS[i]->reset();
        MCPS[i]->setBitrate(CAN_RATE, MCP2515_CRYSTAL_FREQ);
        MCPS[i]->setNormalMode();
    }
#if DEBUG_SERIAL
    Debug_Serial::initialize();
    DBGLN_GENERAL("Debug serial initialized");
#endif
    // Init input pins
    for (int i = 0; i < INPUT_COUNT; i++)
    {
        pinMode(pins_in[i], INPUT);
    }
    // Init output pins
    for (int i = 0; i < OUTPUT_COUNT; i++)
    {
        pinMode(pins_out[i], OUTPUT);
        digitalWrite(pins_out[i], LOW); // initialize output pins to LOW
    }
#if DEBUG_CAN
    Debug_CAN::initialize(&mcp2515_DL); // Currently using motor CAN for debug messages, should change to other
    DBGLN_GENERAL("Debug CAN initialized");
#endif
    DBG_STATUS_CAR(main_car_state.car_status);
    DBGLN_STATUS("Entered INIT");
    DBGLN_GENERAL("Setup complete, entering main loop");
    scheduler.add_task(MCP_MOTOR, scheduler_pedal, 5);
}
References CAN_RATE, car_state::car_status, DBG_STATUS_CAR(), DBGLN_GENERAL(), DBGLN_STATUS(), Debug_Serial::initialize(), Debug_CAN::initialize(), INPUT_COUNT, main_car_state, MCP2515_CRYSTAL_FREQ, mcp2515_DL(), MCP_MOTOR, MCPS, NUM_MCP, OUTPUT_COUNT, pedal, pins_in, pins_out, scheduler, and scheduler_pedal().
Variable Documentation
BMS_MILLIS
constexpr uint16_t BMS_MILLIS = 10000 constexpr
Definition at line 48 of file main.cpp.
Referenced by loop().
brake_pressed
bool brake_pressed = false
Definition at line 52 of file main.cpp.
Referenced by loop().
BRAKE_THRESHOLD
constexpr uint16_t BRAKE_THRESHOLD = 130 constexpr
Definition at line 50 of file main.cpp.
Referenced by loop().
BUSSIN_MILLIS
constexpr uint16_t BUSSIN_MILLIS = 2000 constexpr
Definition at line 47 of file main.cpp.
Referenced by loop().
INPUT_COUNT
constexpr uint8_t INPUT_COUNT = 5 constexpr
Definition at line 24 of file main.cpp.
Referenced by setup().
main_car_state
struct car_state main_car_state
Initial value:
= {
    INIT,
    0,
    0,
    0,
    0,
    false,
    0
}
Global car state structure.
Holds the current state of the car, including status, timers, pedal input, fault flags, and output torque.
Parameters
car_status Current main state of the car (e.g., INIT, DRIVE, etc.).
car_status_millis_counter Millisecond counter for state transitions.
millis Current time in milliseconds.
pedal_final Final processed pedal value.
fault_force_stop True if a fault has triggered a forced stop.
torque_out Output torque value.
Definition at line 66 of file main.cpp.
Referenced by loop(), scheduler_pedal(), and setup().
mcp2515_BMS
BMS bms& mcp2515_BMS
Definition at line 35 of file main.cpp.
MCPS
MCP2515* MCPS[3] = {& mcp2515_DL , &mcp2515_BMS, &mcp2515_DL}
Definition at line 42 of file main.cpp.
Referenced by Scheduler< NUM_TASKS, NUM_MCP2515 >::run_tasks(), and setup().
OUTPUT_COUNT
constexpr uint8_t OUTPUT_COUNT = 4 constexpr
Definition at line 26 of file main.cpp.
Referenced by setup().
pedal
Pedal pedal
Definition at line 77 of file main.cpp.
Referenced by loop(), scheduler_pedal(), setup(), and Pedal::throttle_torque_mapping().
pins_in
constexpr uint8_t pins_in[INPUT_COUNT] = {DRIVE_MODE_BTN, BRAKE_IN, APPS_5V, APPS_3V3, HALL_SENSOR} constexpr
Definition at line 25 of file main.cpp.
Referenced by setup().
pins_out
constexpr uint8_t pins_out[OUTPUT_COUNT] = {FRG, BRAKE_LIGHT, BUZZER, BMS_FAILED_LED} constexpr
Definition at line 27 of file main.cpp.
Referenced by setup().
scheduler
Scheduler< 4, 3 > scheduler(10000, 1000, MCPS) (10000 , 1000 , MCPS)
Referenced by loop(), and setup().
STARTING_MILLIS
constexpr uint16_t STARTING_MILLIS = 2000 constexpr
Definition at line 46 of file main.cpp.
Referenced by loop().
tx_throttle_msg
struct can_frame tx_throttle_msg
Definition at line 44 of file main.cpp.
Referenced by loop(), Pedal::pedal_can_frame_stop_motor(), and Pedal::pedal_can_frame_update().