My Project: Debug_CAN Namespace Reference
Debug_CAN Namespace Reference
Functions
void initialize (MCP2515 *can_interface)
Initializes the Debug_CAN interface with the given MCP2515 CAN controller.
void throttle_in (uint16_t pedal_filtered_1, uint16_t pedal_filtered_2, uint16_t pedal_2_scaled, uint16_t brake)
Sends a debug throttle input message over CAN. This function prepares a CAN frame with the throttle input values and sends it.
void throttle_out (uint16_t throttle_final, int16_t throttle_torque_val)
Sends a debug throttle output message over CAN. This function prepares a CAN frame with the throttle output values and sends it.
void throttle_fault (pedal_fault_status fault_status, uint16_t value)
Sends a debug throttle fault message over CAN. This function prepares a CAN frame with the throttle fault status and sends it.
void throttle_fault (pedal_fault_status fault_status)
Sends a debug throttle fault message over CAN without a float value. This function prepares a CAN frame with the throttle fault status and sends it.
void brake_fault (pedal_fault_status fault_status, uint16_t value)
Sends a debug brake fault message over CAN. This function prepares a CAN frame with the brake fault status and sends it.
void status_car (main_car_status car_status)
Sends a debug car status message over CAN. This function prepares a CAN frame with the current car status and sends it.
void status_brake (uint16_t brake_voltage)
void status_bms (BMS_status BMS_status)
Sends a debug BMS status message over CAN. This function prepares a CAN frame with the current BMS status and sends it.
void hall_sensor (uint16_t hall_sensor_value)
Variables
MCP2515 * can_interface = nullptr
Function Documentation
brake_fault()
void Debug_CAN::brake_fault (pedal_fault_status fault_status, uint16_t value)
Sends a debug brake fault message over CAN. This function prepares a CAN frame with the brake fault status and sends it.
Parameters
fault_status The status of the brake fault as defined in pedal_fault_status enum.
value Optional float value associated with the fault (e.g., brake voltage).
Returns
None
Definition at line 138 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = THROTTLE_FAULT_MSG;
    tx_msg.can_dlc = 3;
    tx_msg.data[0] = static_cast<uint8_t>(fault_status); // Convert enum to uint8_t
    tx_msg.data[1] = value & 0xFF;
    tx_msg.data[2] = (value >> 8) & 0xFF; // Upper byte
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and THROTTLE_FAULT_MSG.
Referenced by DBG_BRAKE_FAULT().
hall_sensor()
void Debug_CAN::hall_sensor (uint16_t hall_sensor_value)
Definition at line 197 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = STATUS_HALL_SENSOR_MSG;
    tx_msg.can_dlc = 2;
    tx_msg.data[0] = hall_sensor_value & 0xFF;
    tx_msg.data[1] = (hall_sensor_value >> 8) & 0xFF; // Upper byte
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and STATUS_HALL_SENSOR_MSG.
Referenced by DBG_HALL_SENSOR().
initialize()
void Debug_CAN::initialize (MCP2515 * can)
Initializes the Debug_CAN interface with the given MCP2515 CAN controller.
This function sets the can_interface pointer to the provided MCP2515 instance. It should be called before using any other Debug_CAN functions.
Parameters
can Pointer to the MCP2515 CAN controller instance.
Returns
None
Definition at line 20 of file Debug_can.cpp.
{
    if (can == nullptr)
        return;
    can_interface = can;
}
References can_interface.
Referenced by setup().
status_bms()
void Debug_CAN::status_bms (BMS_status BMS_status)
Sends a debug BMS status message over CAN. This function prepares a CAN frame with the current BMS status and sends it.
Parameters
BMS_status The current status of the BMS as defined in BMS_status enum.
Returns
None
Definition at line 183 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = STATUS_BMS_MSG;
    tx_msg.can_dlc = 1;
    tx_msg.data[0] = static_cast<uint8_t>(BMS_status); // Convert enum to uint8_t
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and STATUS_BMS_MSG.
Referenced by DBG_BMS_STATUS().
status_brake()
void Debug_CAN::status_brake (uint16_t brake_voltage)
status_car()
void Debug_CAN::status_car (main_car_status car_status)
Sends a debug car status message over CAN. This function prepares a CAN frame with the current car status and sends it.
Parameters
car_status The current status of the car as defined in main_car_status enum.
Returns
None
Definition at line 162 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = STATUS_CAR_MSG;
    tx_msg.can_dlc = 1;
    tx_msg.data[0] = static_cast<uint8_t>(car_status); // Convert enum to uint8_t
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and STATUS_CAR_MSG.
Referenced by DBG_STATUS_CAR().
throttle_fault() [1/2]
void Debug_CAN::throttle_fault (pedal_fault_status fault_status)
Sends a debug throttle fault message over CAN without a float value. This function prepares a CAN frame with the throttle fault status and sends it.
Parameters
fault_status The status of the throttle fault as defined in pedal_fault_status enum.
Returns
None
Definition at line 116 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = THROTTLE_FAULT_MSG;
    tx_msg.can_dlc = 1;
    tx_msg.data[0] = static_cast<uint8_t>(fault_status); // Convert enum to uint8_t
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and THROTTLE_FAULT_MSG.
throttle_fault() [2/2]
void Debug_CAN::throttle_fault (pedal_fault_status fault_status, uint16_t value)
Sends a debug throttle fault message over CAN. This function prepares a CAN frame with the throttle fault status and sends it.
Parameters
fault_status The status of the throttle fault as defined in pedal_fault_status enum.
value Optional float value associated with the fault (e.g., pedal voltage).
Returns
None
Definition at line 92 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = THROTTLE_FAULT_MSG;
    tx_msg.can_dlc = 5;
    tx_msg.data[0] = static_cast<uint8_t>(fault_status); // Convert enum to uint8_t
    tx_msg.data[1] = value & 0xFF;
    tx_msg.data[2] = (value >> 8) & 0xFF; // Upper byte
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and THROTTLE_FAULT_MSG.
Referenced by DBG_THROTTLE_FAULT().
throttle_in()
void Debug_CAN::throttle_in (uint16_t pedal_filtered_1, uint16_t pedal_filtered_2, uint16_t pedal_2_scaled, uint16_t brake)
Sends a debug throttle input message over CAN. This function prepares a CAN frame with the throttle input values and sends it.
Parameters
pedal_filtered_1 Filtered value from pedal sensor 1.
pedal_filtered_2 Filtered value from pedal sensor 2.
pedal_2_scaled Scaled value of pedal sensor 2.
Returns
None
Definition at line 36 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = THROTTLE_IN_MSG;
    tx_msg.can_dlc = 8;
    // Little-endian format for uint16_t values
    tx_msg.data[0] = pedal_filtered_1 & 0xFF;
    tx_msg.data[1] = (pedal_filtered_1 >> 8) & 0xFF; // Upper byte
    tx_msg.data[2] = pedal_filtered_2 & 0xFF;
    tx_msg.data[3] = (pedal_filtered_2 >> 8) & 0xFF; // Upper byte
    tx_msg.data[4] = pedal_2_scaled & 0xFF;
    tx_msg.data[5] = (pedal_2_scaled >> 8) & 0xFF; // Upper byte
    tx_msg.data[6] = brake & 0xFF;
    tx_msg.data[7] = (brake >> 8) & 0xFF; // Upper byte
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and THROTTLE_IN_MSG.
Referenced by DBG_THROTTLE_IN().
throttle_out()
void Debug_CAN::throttle_out (uint16_t throttle_final, int16_t throttle_torque_val)
Sends a debug throttle output message over CAN. This function prepares a CAN frame with the throttle output values and sends it.
Parameters
throttle_final Final value of the throttle pedal.
throttle_torque_val Calculated torque value based on the throttle input.
Returns
None
Definition at line 66 of file Debug_can.cpp.
{
    if (!can_interface)
        return;
    can_frame tx_msg;
    tx_msg.can_id = THROTTLE_OUT_MSG;
    tx_msg.can_dlc = 4;
    // Little-endian format for int16_t value
    tx_msg.data[0] = throttle_final & 0xFF;
    tx_msg.data[1] = (throttle_final >> 8) & 0xFF; // Upper byte
    tx_msg.data[2] = throttle_torque_val & 0xFF;
    tx_msg.data[3] = (throttle_torque_val >> 8) & 0xFF; // Upper byte
    can_interface->sendMessage(&tx_msg);
}
References can_interface, and THROTTLE_OUT_MSG.
Referenced by DBG_THROTTLE_OUT().
Variable Documentation
can_interface
MCP2515 * Debug_CAN::can_interface = nullptr extern
Definition at line 9 of file Debug_can.cpp.
Referenced by brake_fault(), hall_sensor(), initialize(), status_bms(), status_car(), throttle_fault(), throttle_in(), and throttle_out().