My Project: Debug_Serial Namespace Reference
Debug_Serial Namespace Reference
Functions
void initialize ()
Initializes the Debug_Serial interface. This function sets up the serial communication for debugging purposes. It should be called before using any other Debug_Serial functions.
void print (const char *msg)
Prints a message to the serial console. This function sends a string message to the serial console for debugging.
void println (const char *msg)
Prints a line to the serial console. This function sends a string message followed by a newline to the serial console for debugging.
void throttle_in (uint16_t pedal_filtered_1, uint16_t pedal_filtered_2, uint16_t pedal_filtered_final, uint16_t brake)
Prints a throttle input message to the serial console. This function formats and sends the throttle input values to the serial console.
void throttle_out (uint16_t throttle_final, int16_t throttle_torque_val)
Prints a throttle output message to the serial console. This function formats and sends the throttle output values to the serial console.
void throttle_fault (pedal_fault_status fault_status, uint16_t value)
Prints a throttle fault message to the serial console. This function formats and sends the throttle fault status and value to the serial console.
void throttle_fault (pedal_fault_status fault_status)
Prints a throttle fault message to the serial console without a float value. This function formats and sends the throttle fault status to the serial console.
void brake_fault (pedal_fault_status fault_status, uint16_t value)
Prints a brake fault message to the serial console. This function formats and sends the brake fault status and value to the serial console.
void status_car (main_car_status car_status)
Prints the current car status to the serial console. This function formats and sends the current car status to the serial console.
void status_brake (uint16_t brake_voltage)
void status_bms (BMS_status BMS_status)
Prints the current BMS status to the serial console. This function formats and sends the current BMS status to the serial console.
void hall_sensor (uint16_t hall_sensor_value)
Function Documentation
brake_fault()
void Debug_Serial::brake_fault (pedal_fault_status fault_status, uint16_t value)
Prints a brake fault message to the serial console. This function formats and sends the brake fault status and value to the serial console.
Parameters
fault_status The status of the brake fault as defined in pedal_fault_status enum.
value brake ADC reading
Returns
None
Definition at line 140 of file Debug_serial.cpp.
{
    switch (fault_status)
    {
    case NONE:
        break;
    case BRAKE_LOW:
        Serial.print("Brake input too low. Value: ");
        Serial.println(value);
        break;
    case BRAKE_HIGH:
        Serial.print("Brake too high. Value: ");
        Serial.println(value);
        break;
    default:
        Serial.println("Unknown fault status");
        break;
    }
}
References BRAKE_HIGH, BRAKE_LOW, and NONE.
Referenced by DBG_BRAKE_FAULT().
hall_sensor()
void Debug_Serial::hall_sensor (uint16_t hall_sensor_value)
Definition at line 246 of file Debug_serial.cpp.
{
    void(Serial.print("Hall Sensor Value: "));
    void(Serial.println(hall_sensor_value));
}
Referenced by DBG_HALL_SENSOR().
initialize()
void Debug_Serial::initialize ()
Initializes the Debug_Serial interface. This function sets up the serial communication for debugging purposes. It should be called before using any other Debug_Serial functions.
Parameters
None
Returns
None
Definition at line 12 of file Debug_serial.cpp.
{
    Serial.begin(115200);
}
Referenced by setup().
print()
void Debug_Serial::print (const char * msg)
Prints a message to the serial console. This function sends a string message to the serial console for debugging.
Parameters
msg The message to print.
Returns
None
Definition at line 24 of file Debug_serial.cpp.
{ Serial.print(msg); }
Referenced by DBG_GENERAL(), DBG_STATUS(), and DBG_THROTTLE().
println()
void Debug_Serial::println (const char * msg)
Prints a line to the serial console. This function sends a string message followed by a newline to the serial console for debugging.
Parameters
msg The message to print.
Returns
None
Definition at line 33 of file Debug_serial.cpp.
{ Serial.println(msg); }
Referenced by DBGLN_GENERAL(), DBGLN_STATUS(), and DBGLN_THROTTLE().
status_bms()
void Debug_Serial::status_bms (BMS_status BMS_status)
Prints the current BMS status to the serial console. This function formats and sends the current BMS status to the serial console.
Parameters
BMS_status The current status of the BMS as defined in BMS_status enum.
Returns
None
Definition at line 219 of file Debug_serial.cpp.
{
    switch (BMS_status)
    {
    case NO_MSG:
        Serial.println("BMS Status: No message received");
        break;
    case WRONG_ID:
        Serial.println("BMS Status: Wrong ID");
        break;
    case WAITING:
        Serial.println("BMS Status: Waiting to start");
        break;
    case STARTING:
        Serial.println("BMS Status: Starting");
        break;
    case STARTED:
        Serial.println("BMS Status: Started");
        break;
    default:
        Serial.println("BMS Status: UNKNOWN");
        break;
    }
}
References NO_MSG, STARTED, STARTING, WAITING, and WRONG_ID.
Referenced by DBG_BMS_STATUS().
status_brake()
void Debug_Serial::status_brake (uint16_t brake_voltage)
status_car()
void Debug_Serial::status_car (main_car_status car_status)
Prints the current car status to the serial console. This function formats and sends the current car status to the serial console.
Parameters
car_status The current status of the car as defined in main_car_status enum.
Returns
None
Definition at line 167 of file Debug_serial.cpp.
{
    static main_car_status last_status = INIT;
    if (car_status != last_status) {
        Serial.print("Car Status: ");
        switch (last_status)
        {
        case INIT:
            Serial.print("INIT -> ");
            break;
        case STARTIN:
            Serial.print("STARTIN -> ");
            break;
        case BUSSIN:
            Serial.print("BUSSIN -> ");
            break;
        case DRIVE:
            Serial.print("DRIVE -> ");
            break;
        default:
            Serial.print("UNKNOWN -> ");
            break;
        }
        switch (car_status)
        {
        case INIT:
            Serial.print("INIT -> ");
            break;
        case STARTIN:
            Serial.print("STARTIN -> ");
            break;
        case BUSSIN:
            Serial.print("BUSSIN -> ");
            break;
        case DRIVE:
            Serial.print("DRIVE -> ");
            break;
        default:
            Serial.print("UNKNOWN -> ");
            break;
        }
        last_status = car_status;
    }
}
References BUSSIN, DRIVE, INIT, and STARTIN.
Referenced by DBG_STATUS_CAR().
throttle_fault() [1/2]
void Debug_Serial::throttle_fault (pedal_fault_status fault_status)
Prints a throttle fault message to the serial console without a float value. This function formats and sends the throttle fault status to the serial console.
Parameters
fault_status The status of the throttle fault as defined in pedal_fault_status enum.
Returns
None
Definition at line 111 of file Debug_serial.cpp.
{
    switch (fault_status)
    {
    case NONE:
        break;
    case DIFF_START:
        Serial.println("Pedal mismatch just started");
        break;
    case DIFF_EXCEED_100MS:
        Serial.println("FATAL FAULT: Pedal mismatch persisted > 100ms!");
        break;
    case DIFF_RESOLVED:
        Serial.println("Pedal mismatch resolved");
        break;
    default:
        Serial.println("Unknown fault status");
        break;
    }
}
References DIFF_EXCEED_100MS, DIFF_RESOLVED, DIFF_START, and NONE.
throttle_fault() [2/2]
void Debug_Serial::throttle_fault (pedal_fault_status fault_status, uint16_t value)
Prints a throttle fault message to the serial console. This function formats and sends the throttle fault status and value to the serial console.
Parameters
fault_status The status of the throttle fault as defined in pedal_fault_status enum.
value Optional value associated with the fault
Returns
None
Definition at line 80 of file Debug_serial.cpp.
{
    switch (fault_status)
    {
    case NONE:
        break;
    case DIFF_CONTINUING:
        Serial.print("Pedal mismatch continuing. Difference: ");
        Serial.println(value);
        break;
    case THROTTLE_LOW:
        Serial.print("Throttle input too low. Value: ");
        Serial.println(value);
        break;
    case THROTTLE_HIGH:
        Serial.print("Throttle too high. Value: ");
        Serial.println(value);
        break;
    default:
        Serial.println("Unknown fault status");
        break;
    }
}
References DIFF_CONTINUING, NONE, THROTTLE_HIGH, and THROTTLE_LOW.
Referenced by DBG_THROTTLE_FAULT().
throttle_in()
void Debug_Serial::throttle_in (uint16_t pedal_1, uint16_t pedal_2, uint16_t pedal_2_scaled, uint16_t brake)
Prints a throttle input message to the serial console. This function formats and sends the throttle input values to the serial console.
Parameters
pedal_1 Value from pedal sensor 1.
pedal_2 Value from pedal sensor 2.
pedal_2_scaled Scaled value of pedal sensor 2.
Returns
None
Definition at line 44 of file Debug_serial.cpp.
{
    Serial.print("Pedal 1: ");
    Serial.print(pedal_1);
    Serial.print(" | Pedal 2: ");
    Serial.print(pedal_2);
    Serial.print(" | Pedal 2 scaled: ");
    Serial.print(pedal_2_scaled);
    Serial.print(" | Brake: ");
    Serial.println(brake);
}
Referenced by DBG_THROTTLE_IN().
throttle_out()
void Debug_Serial::throttle_out (uint16_t throttle_final, int16_t throttle_torque_val)
Prints a throttle output message to the serial console. This function formats and sends the throttle output values to the serial console.
Parameters
throttle_final Final value of the throttle pedal.
throttle_torque_val Calculated torque value based on the throttle input.
Returns
None
Definition at line 64 of file Debug_serial.cpp.
{
    Serial.print("Throttle Final: ");
    Serial.print(throttle_final);
    Serial.print(" | Torque Value: ");
    Serial.println(throttle_torque_val);
}
Referenced by DBG_THROTTLE_OUT().